### ISSUE TITLE
how to use this repository?

### ISSUE THREAD

**Issue by ghost** [hbldh/skboost#1]
hi

i'm an amateur python programmer. however, i want to work with milboost and gentleboost with other datasets (from scikit-learn or .csv files) but, unfortunately, i don't know how.

i'll be grateful if you guided me on how to do so...

**Comment by hbldh** [comment]
Check the `scripts` folder in the repo for examples: https://github.com/hbldh/skboost/tree/master/scripts

It should hade named examples, sorry.

Be aware that it was some time since I used this, so it may be out of date with recent scikit-learn versions. Just let me know in that case and we will work it out!

Good luck!

**Comment by ghost** [comment]
Hi

first of all, i appreciate you responding to my issue.

second of all, i ran that very script; however, i got an error that i don't
have any module named 'skboost'. i reference to picture 11 which i attached.

third and last, i tried to install that package with that name via pip, but
there was no package suitable with the version of my pc or laptop. i
reference to picture 12 which i attached.

i want to use milboost and gentleboost for a research paper. and i will
reference you, your work/repository in my paper or anyone's that i can find
comfortable to work with. i will be forever grateful if you help me on this
so i can make it work with general datasets and probable other datasets.

yours truly,
Alireza Rashidi
